# Jürgen Berger 2019
#
# Tries to find libharfbuzz and sets following variables according to found capabilities:
#
# HARFBUZZ_FOUND
# HARFBUZZ_INCLUDE_DIRS
# HARFBUZZ_LIBRARIES

FIND_PACKAGE(PkgConfig)
PKG_CHECK_MODULES(PKG_HARFBUZZ harfbuzz)

FIND_PATH(HARFBUZZ_INCLUDE_DIRS harfbuzz/hb.h
  HINTS
    ${PKG_HARFBUZZ_INCLUDE_DIRS}
    ${PKG_HARFBUZZ_INCLUDEDIR}
  PATH_SUFFIXES harfbuzz
)

FIND_LIBRARY(harfbuzz_LIBRARIES harfbuzz
  HINTS ${PKG_HARFBUZZ_LIBRARY_DIRS}
)

IF(HARFBUZZ_LIBRARIES AND HARFBUZZ_INCLUDE_DIRS)
  SET(HARFBUZZ_FOUND true)
ENDIF()

IF(HARFBUZZ_FIND_REQUIRED AND NOT HARFBUZZ_FOUND)
  MESSAGE(FATAL_ERROR "Could not find HARFBUZZ")
ENDIF()
